name: 01 - Building Blocks
on: [push, workflow_dispatch]

jobs:
  first-job:
    name: "echo-hello"
    runs-on: ubuntu-latest
    steps:
      - name: "Say hello"
        run: echo "Hello, World!"
  second-job:
    name: "echo-goodbye"
    runs-on: ubuntu-latest
    steps:
      - name: "I will fail"
        run: |
          echo "I will fail this job"
          exit 1  # Change to 'exit 1' to simulate failure
      - name: "Say goodbye"
        run: echo "Goodbye!"