name: 02 - Workflow Events
on: push
jobs:
  first-job:
    name: "echo"
    runs-on: ubuntu-latest
    steps:
      - name: "Show the trigger"
        run: |
          echo "This workflow was triggered by a push event."
          exit 0