name: My workflow
on:
  workflow_dispatch:
    inputs:
      first_input:
        type: choice
        description: 'Choose input'
        options:
          - input_test
          - input_prod

      second_input:
        type: choice
        description: 'Choose input'
        options:
          - android
          - ios

jobs:
  my-first-job:
    runs-on: windows-latest
    steps:
      - run: echo "Hello, World!"
  my-second-job:
    runs-on: windows-latest
    steps:
      - run: echo "This is my second job."