name: My workflow
on: push

jobs:
  my-first-job:
    runs-on: windows-latest
    steps:
      - run: echo "Hello, World!"
  my-second-job:
    runs-on: windows-latest
    steps:
      - run: echo "This is my second job."